FROM mcr.microsoft.com/devcontainers/javascript-node:20-bookworm

# Install additional OS packages
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends \
#     mongodb-clients \
#     vim \
#     && apt-get clean -y && rm -rf /var/lib/apt/lists/*



# Set the working directory
WORKDIR /workspace

# Expose ports
EXPOSE 5173 3000
